name: prebuild

on:
  push:
  workflow_dispatch:
    inputs:
      dryrun:
        default: true
        required: false
        type: boolean

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        otp:
          #- 24.3.4.6
#          - 23.3.4.18
          #- 25.3
          - 26.2.5.3
        os:
          - ubuntu-22.04
          #- ubuntu-20.04
        type:
          - otp
          - "otp-lttng"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fake Build ${{ matrix.otp  }}
        if: ${{ inputs.dryrun }}
        env:
          otp_vsn: ${{ matrix.otp }}
          os: ${{ matrix.os }}
          type: ${{ matrix.type }}
        run: |
          ./kerl update releases
          cp ./kerl $HOME/.kerl/
          tar czvf "${type}-${otp_vsn}-${os}.tar.gz" -C $HOME .kerl

      - name: Build ${{ matrix.otp  }}
        if: ${{ ! inputs.dryrun }}
        env:
          otp_vsn: ${{ matrix.otp }}
          os: ${{ matrix.os }}
          type: ${{ matrix.type }}
        run: |
          export KERL_RELEASE_TARGET="debug asan opt gcov gprof valgrind lcnt"
          export KERL_CONFIGURE_OPTIONS="--disable-hipe --with-odbc"

          if [[ ${type} == "otp-lttng" ]]; then
            sudo apt-add-repository ppa:lttng/stable-2.12
            sudo apt-get update
            sudo apt-get install -y lttng-tools babeltrace liblttng-ust-dev lttng-modules-dkms- \
                   git curl libssl-dev make automake autoconf libncurses-dev gcc g++ default-jdk \
                   unixodbc-dev libwxgtk3.2-dev libwxgtk-webview3.2-dev xsltproc \
                   libxml2-utils libsctp-dev lksctp-tools software-properties-common shellcheck \
                   shfmt
            export KERL_CONFIGURE_OPTIONS="--with-dynamic-trace=lttng ${KERL_CONFIGURE_OPTIONS}"
          fi

          ./kerl update releases
          ./kerl build "${otp_vsn}" "${otp_vsn}"

          cp ./kerl $HOME/.kerl/

          tar czvf "${type}-${otp_vsn}-${os}.tar.gz" -C $HOME .kerl

      - name: cat failed build log
        if: failure()
        run: |
           cat ~/.kerl/builds/*/*.log

      - name: Archive failed build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log-${{matrix.otp}}-${{matrix.os}}-${{matrix.type}}
          path: ~/.kerl/builds/${{matrix.otp}}/otp_build_${{matrix.otp}}.log
          retention-days: 1

      - uses: actions/upload-artifact@v4
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: packages
          path: |
            *.tar.gz

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.Release.outputs.upload_url  }}
          asset_path: "${{ matrix.type }}-${{ matrix.otp }}-${{ matrix.os }}.tar.gz"
          asset_name: "${{ matrix.type }}-${{ matrix.otp }}-${{ matrix.os }}.tar.gz"
          asset_content_type: application/zip


  release:
    runs-on: ubuntu-latest
    needs:
      - linux
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: 'otp-*'
          path: packages
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2.0.5
        with:
          name: kerl otp ${{ github.ref_name }} Released
          body: kerl otp  ${{ github.ref_name }} Released
          files: packages/*
          draft: false
          prerelease: false
